services:
  - type: web
    name: demo-spring-boot
    runtime: docker
    dockerfilePath: ./Dockerfile
    env: docker
    region: frankfurt  # or your preferred region
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: db_tp8_mc17
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: db_tp8_mc17
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db_tp8_mc17
          property: password
      - key: DB_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
    healthCheckPath: /actuator/health

databases:
  - name: db_tp8_mc17
    databaseName: db_tp8_mc17
    user: db_tp8_mc17_user
    plan: free
